sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t naenaenae/docker-react -f Dockerfile.dev . 
  
script:
  - docker container run -e CI=true naenaenae/docker-react npm run test

